service: aws-serverless-java-example

provider:
  name: aws
  runtime: java8
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:*"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource: "*"

resources:
  Resources:
    productsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: users
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: name
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: name
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

package:
  artifact: target/serverless.jar

functions:
  usdToUah:
    handler: com.haraiev.serverless.handler.USDHandler
    events:
      - http:
          path: /usd
          method: get
  s3ToDynamoDB:
    handler: com.haraiev.serverless.handler.S3Handler
    events:
      - s3:
          bucket: text-files-bucket
          event: s3:ObjectCreated:*
